#!/bin/bash
# Moodle Git仓库设置指南
# 此脚本包含将Moodle项目迁移到自己GitHub仓库的完整步骤

echo "=========================================="
echo "Moodle Git仓库设置指南"
echo "=========================================="
echo ""
echo "⚠️  请仔细阅读每一步，手动执行命令，不要直接运行此脚本！"
echo ""

# ===== 步骤1: 备份当前配置 =====
echo "===== 步骤1: 备份当前Git配置 ====="
echo "cd /c/c/moodle"
echo "cp -r .git .git.backup"
echo "cp .git/config .git.config.backup"
echo ""

# ===== 步骤2: 查看子模块状态 =====
echo "===== 步骤2: 查看现有子模块状态 ====="
echo "# 检查 theme/academi"
echo "cd theme/academi"
echo "git remote -v"
echo "git status"
echo "ACADEMI_REMOTE=\$(git remote get-url origin)"
echo "cd ../.."
echo ""
echo "# 检查 mod/questionnaire"
echo "cd mod/questionnaire"
echo "git remote -v"
echo "git status"
echo "QUESTIONNAIRE_REMOTE=\$(git remote get-url origin)"
echo "cd ../.."
echo ""

# ===== 步骤3: 移除Moodle官方远程仓库 =====
echo "===== 步骤3: 移除Moodle官方远程仓库 ====="
echo "git remote remove origin"
echo "git remote -v  # 验证已移除"
echo ""

# ===== 步骤4: 创建.gitignore文件 =====
echo "===== 步骤4: 创建.gitignore文件 ====="
echo "# 将.gitignore.example重命名为.gitignore并根据需要修改"
echo "cp .gitignore.example .gitignore"
echo ""
echo "# 或者手动创建.gitignore文件"
echo "# 确保排除Moodle核心文件，只跟踪自定义内容"
echo ""

# ===== 步骤5: 添加自己的GitHub远程仓库 =====
echo "===== 步骤5: 添加自己的GitHub远程仓库 ====="
echo "# 替换成您的GitHub仓库地址"
echo "git remote add origin https://github.com/YOUR_USERNAME/my-moodle-project.git"
echo "git remote -v  # 验证"
echo ""

# ===== 步骤6: 初始化子模块配置 =====
echo "===== 步骤6: 配置子模块 ====="
echo "# 移除子模块的.git目录（暂时）"
echo "mv theme/academi/.git theme/academi/.git.backup"
echo "mv mod/questionnaire/.git mod/questionnaire/.git.backup"
echo ""
echo "# 添加为子模块"
echo "git submodule add <academi-repo-url> theme/academi"
echo "git submodule add <questionnaire-repo-url> mod/questionnaire"
echo ""
echo "# 或者手动创建.gitmodules文件"
echo "cat > .gitmodules << 'EOF'"
echo "[submodule \"theme/academi\"]"
echo "    path = theme/academi"
echo "    url = <your-academi-repo-url>"
echo "[submodule \"mod/questionnaire\"]"
echo "    path = mod/questionnaire"
echo "    url = <your-questionnaire-repo-url>"
echo "EOF"
echo ""

# ===== 步骤7: 添加和提交更改 =====
echo "===== 步骤7: 添加和提交更改 ====="
echo "# 检查将要提交的文件"
echo "git status"
echo ""
echo "# 添加文件"
echo "git add .gitignore"
echo "git add .gitmodules"
echo "git add admin/cli/upload_user_pictures_batch.php"
echo "git add admin/tool/uploaduser/picture_batch.php"
echo "git add admin/tool/uploaduser/picture_batch_form.php"
echo "git add admin/tool/uploaduser/settings.php"
echo "git add admin/tool/uploaduser/lang/"
echo "git add config-dist.php"
echo ""
echo "# 再次检查"
echo "git status"
echo ""
echo "# 提交"
echo "git commit -m \"Initial commit: Custom Moodle configuration and tools\""
echo ""

# ===== 步骤8: 推送到GitHub =====
echo "===== 步骤8: 推送到GitHub ====="
echo "# 创建主分支"
echo "git branch -M main"
echo ""
echo "# 首次推送"
echo "git push -u origin main"
echo ""

# ===== 步骤9: 在生产服务器上设置 =====
echo "===== 步骤9: 在生产服务器上设置 ====="
echo "# 在生产服务器上执行："
echo ""
echo "# 1. 备份生产环境"
echo "cd /path/to/production/moodle"
echo "cp -r . ../moodle.backup"
echo ""
echo "# 2. 初始化Git（如果还没有）"
echo "git init"
echo ""
echo "# 3. 添加远程仓库"
echo "git remote add origin https://github.com/YOUR_USERNAME/my-moodle-project.git"
echo ""
echo "# 4. 创建.gitignore（与开发环境相同）"
echo "# 复制开发环境的.gitignore文件"
echo ""
echo "# 5. 拉取代码"
echo "git fetch origin"
echo "git checkout -b main origin/main"
echo ""
echo "# 6. 初始化子模块"
echo "git submodule init"
echo "git submodule update"
echo ""

# ===== 步骤10: 日常使用流程 =====
echo "===== 步骤10: 日常使用流程 ====="
echo ""
echo "【开发环境】修改代码后："
echo "git add <modified-files>"
echo "git commit -m \"描述修改内容\""
echo "git push origin main"
echo ""
echo "【生产环境】更新代码："
echo "git pull origin main"
echo "git submodule update --remote  # 如果子模块也有更新"
echo ""

echo "=========================================="
echo "设置完成！"
echo "=========================================="
echo ""
echo "⚠️  重要提醒："
echo "1. 确保.gitignore正确配置，不要提交config.php（包含数据库密码）"
echo "2. 不要提交moodledata目录"
echo "3. 子模块的更新需要单独处理"
echo "4. 生产环境拉取代码前先备份"
echo ""
